export const data = [
  {
    title: 'Category',
    categoryData: [
      {
        id: 1,
        name: 'Metals',
        image: require('../assets/Icons/rust.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 2,
        name: 'Spices',
        image: require('../assets/Icons/spice.png'),
        description: 'Some Ranmdom Spices Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Commodity',
        image: require('../assets/Icons/commodity.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Fooder',
        image: require('../assets/Icons/food.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Metals',
        image: require('../assets/Icons/rust.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 2,
        name: 'Spices',
        image: require('../assets/Icons/spice.png'),
        description: 'Some Ranmdom Spices Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Commodity',
        image: require('../assets/Icons/commodity.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Fooder',
        image: require('../assets/Icons/food.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Fooder',
        image: require('../assets/Icons/food.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Fooder',
        image: require('../assets/Icons/food.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Fooder',
        image: require('../assets/Icons/food.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Fooder',
        image: require('../assets/Icons/food.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },
      {
        id: 1,
        name: 'Fooder',
        image: require('../assets/Icons/food.png'),
        description: 'Some Ranmdom Description',
        subCategory: null,
      },

    ],
  },
  {
    title: 'Product Suite',
    productData: [
      {
        id: 12,
        name: 'Basmati Rice',
        category: 'Spices',
        description: 'Some Basmati Description',
        image: 'https://null',
        categoryId: 2,
      },
      {
        id: 122,
        name: 'Steel ',
        category: 'Metals',
        description: 'Some Basmati Description',
        image: 'https://null',
        categoryId: 1,
      },
    ],
  },
];
