platform :android do

  desc 'Generate Android APK'
  lane :generateBuild do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'bundle', build_type: 'release', project_dir: 'android/')
     slack(
        message: "AHTrade Android App APK Has been Generated Successfully.",
        success: true,
        slack_url: "https://hooks.slack.com/services/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",
        default_payloads: [:git_branch, :git_branch, :git_author, :last_git_commit, :last_git_commit_hash],
        payload: {
            "Build Date" => Time.new.to_s,
            "Built By" => "FastLane Android Build Pipeline",
            "OS" => "Android"
        }
      )
  end
  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'bundle', build_type: 'release', project_dir: 'android/')
  end
  desc 'Build and upload to App Center.'
  lane :beta do
  build
  appcenter_upload(
      api_token: "1c44b5a107d355237e6e8df0c6d56e66dfa62069",
      owner_name: "Atlashorizon",
      app_name: "AHTrade",
      apk: "/Users/lakshu17/Desktop/AHTrade/android/app/build/outputs/bundle/release/app-release.aab"
  )
  slack(
    message: "AHTrade Android App Has been Uploaded Successfully to AppCenter.Ready for Testing",
    success: true,
    slack_url: "https://hooks.slack.com/services/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",
    default_payloads: [:git_branch, :git_branch, :git_author, :last_git_commit, :last_git_commit_hash],
    payload: {
        "Build Date" => Time.new.to_s,
        "Built By" => "FastLane Android Pipeline",
        "OS" => "Android"
    }
  )
  end
  desc 'Upload App to PlayStore'
  lane :playstore do
    build
    upload_to_play_store(track: 'beta')
    slack(
        message: "AHTrade Android App Has been Uploaded Successfully to Google PlayStore.Ready for Deployment",
        success: true,
        slack_url: "https://hooks.slack.com/services/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",
        default_payloads: [:git_branch, :git_branch, :git_author, :last_git_commit, :last_git_commit_hash],
        payload: {
            "Build Date" => Time.new.to_s,
            "Built By" => "FastLane Android Pipeline",
            "OS" => "Android"
        }
    )
  end
end
