platform :android do

  desc 'Generate Android APK'
  lane :generateBuild do
    incrementVersionCode
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'bundle', build_type: 'release', project_dir: 'android/')
    slack(
        message: "AHTrade Android App APK Has been Generated Successfully.",
        success: true,
        slack_url: "https://hooks.slack.com/services/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",
        default_payloads: [:git_branch, :git_branch, :git_author, :last_git_commit, :last_git_commit_hash],
        payload: {
            "Build Date" => Time.new.to_s,
            "Built By" => "FastLane Android Build Pipeline",
            "OS" => "Android"
        }
      )
  end
 desc "Increment Version Code"
  lane :incrementVersionCode do
   increment_version_code(
              gradle_file_path: "./android/app/build.gradle",
              #ext_constant_name: "test"
              #app_folder_name:"app"
        )
    end
  desc "Get Version Name"
    lane :getVersionName do
      value = get_version_name(
               gradle_file_path:"./app/build.gradle",
               #ext_constant_name:"versionName"
               )
      value
  end
  desc "Get Version Code"
    lane :getVersionCode do
       code =  get_version_code(
                        #app_folder_name:"project"
                        gradle_file_path:"./app/build.gradle",
                        #ext_constant_name:"versionName"
       )
      code
  end
  desc 'Build the Android application.'
  lane :build do
    incrementVersionCode
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'bundle', build_type: 'release', project_dir: 'android/')
  end
  desc 'Build and upload to App Center.'
  lane :beta do
  build
  appcenter_upload(
      api_token: "1c44b5a107d355237e6e8df0c6d56e66dfa62069",
      owner_name: "Atlashorizon",
      app_name: "AHTrade",
      apk: "/Users/lakshu17/Desktop/AHTrade/android/app/build/outputs/bundle/release/app-release.aab"
  )
  slack(
    message: "AHTrade Android App Has been Uploaded Successfully to AppCenter.Ready for Testing",
    success: true,
    slack_url: "https://hooks.slack.com/services/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",
    default_payloads: [:git_branch, :git_branch, :git_author, :last_git_commit, :last_git_commit_hash],
    payload: {
        "Build Date" => Time.new.to_s,
        "Built By" => "FastLane Android Pipeline",
        "OS" => "Android OS"
    }
  )
  end
  desc 'Upload App to PlayStore'
  lane :playstore do
    build
    upload_to_play_store(track: 'fastlane')
    vName = getVersionName
    vCode = getVersionCode
    slack(
        message: "AHTrade Android App Has been Uploaded Successfully to Google PlayStore.Ready for Deployment",
        success: true,
        slack_url: "https://hooks.slack.com/services/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",
        default_payloads: [:git_branch, :git_branch, :git_author, :last_git_commit, :last_git_commit_hash],
        payload: {
            "Build Date" => Time.new.to_s,
            "Built By" => "FastLane Android Pipeline",
            "OS" => "Android",
            "VersionName" => vName,
            "VersionCode" => vCode
        }
    )
  end
end
